# build environment
FROM node:10.12.0-alpine as builder
RUN mkdir /src
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
COPY package.json /src/package.json
RUN npm install
RUN npm install react-scripts@2.0.3 -g
COPY . /src
RUN npm run build

# production environment
FROM nginx:1.15-alpine
COPY --from=builder /src/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
