version: '3'

volumes:
  static_files:
  media:
  conf:
  pgdata:
  frontend:

services:
  frontend:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile-prod
      args:
        - REACT_APP_API_URL=http://localhost:8000/api/publications/
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production
    depends_on:
      - webapp
    ports:
      - 80:80
  webapp:
    container_name: webapp
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: gunicorn -w 4 api.wsgi:application -b 0.0.0.0:8080
    volumes:
      - ./web/static_files:/src/static_files
    ports:
      - 8080:8080
    environment:
      DJANGO_SETTINGS_MODULE: api.settings-prod
    env_file:
      - ./postgres/db.env
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: postgres
    env_file:
      - ./postgres/db.env
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  server:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./web/static_files:/src/static_files
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
      - frontend