version: '3'

volumes:
  static_files:
  media:
  conf:
  pgdata:
  frontend:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile-prod
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000/api/publications/
    depends_on:
      - backend
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: gunicorn -w 4 api.wsgi:application -b 0.0.0.0:8080
    volumes:
      - ./backend/static_files:/src/static_files
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: api.settings-prod
    env_file:
      - ./postgres/db.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:10
    env_file:
      - ./postgres/db.env
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
