version: '3'

volumes:
  pgdata:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api/publications/
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings-dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:10
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
