version: '3'

volumes:
  static_files:
  media:
  conf:
  pgdata:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/frontend
    ports:
      - 80:80
    depends_on:
      - db
  webapp:
    container_name: webapp
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: gunicorn -w 4 api.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./web/static_files:/web/static_files
      - ./web/media:/web/media
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: api.settings-prod
    env_file:
      - ./postgres/db.env
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: postgres
    env_file:
      - ./postgres/db.env
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  server:
    container_name: server
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./web/static_files:/web/static_files
      - ./web/media:/web/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
