version: '3'

volumes:
  pgdata:

services:
  frontend:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
    depends_on:
      - webapp
  webapp:
    container_name: django
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: python3 ./web/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings-dev
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
