# Generated by Django 2.1.1 on 2018-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=63, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('citation', models.TextField(blank=True, default='Unavailable')),
                ('container', models.CharField(blank=True, max_length=127, null=True)),
                ('pub_type', models.CharField(blank=True, max_length=63, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
